# Bot -> Consumer -> Consumer-logs 
version: '3.9'

services:
  bot_consumer:
    build:
      context: ..
      dockerfile: Dockerfile

    container_name: "bot-faststream"

    environment:
      KAFKA_URL: ${KAFKA_URL:?}
  
    ports: 
      - "${API_PORT}:8000"

    volumes:
      - ../app/:/app/
      - ../.env:/app/.env

    command: "debugpy --listen 0.0.0.0:5678 -m faststream run --factory consumers.main:get_app --reload"